### ISSUE TITLE
 An error is reported when using getGEO to download data.

### ISSUE THREAD

**Issue by 1298894527** [seandavi/GEOquery#107]
> gset<-getGEO('GSE60502', destdir=".",getGPL = F)
Found 1 file(s)
GSE60502_series_matrix.txt.gz
Using locally cached version: ./GSE60502_series_matrix.txt.gz
error: 'C:\Users\star\AppData\Local\Temp\Rtmp4MLEYN\file22901f201c9' does not exist.

**Comment by seandavi** [comment]
I'm not able to reproduce your error. I'd suggest restarting R and trying again. It is possible that the R temp directory was deleted or some other filesystem problem occurred. If you still have problems after restarting R and ensuring that you are using the most recent version of R and GEOquery, it would be helpful to have the output of `sessionInfo()` when the error occurs. 

I'm going to close for now, but feel free to reopen if you still have problems.

**Comment by 1298894527** [comment]
Thanks for your reply, I have found my problem and solved it.


Thank you again for your enthusiasm.Happy New Year！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sean Davis"<notifications@github.com&gt;; 
发送时间: 2021年1月2日(星期六) 上午9:35
收件人: "seandavi/GEOquery"<GEOquery@noreply.github.com&gt;; 
抄送: "尽吹散"<1298894527@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [seandavi/GEOquery]  An error is reported when using getGEO to download data. (#107)





 
I'm not able to reproduce your error. I'd suggest restarting R and trying again. It is possible that the R temp directory was deleted or some other filesystem problem occurred. If you still have problems after restarting R and ensuring that you are using the most recent version of R and GEOquery, it would be helpful to have the output of sessionInfo() when the error occurs.
 
I'm going to close for now, but feel free to reopen if you still have problems.

**Comment by kktt520** [comment]
could you please tell  me how to solve this problem? I had a same error as you

**Comment by 1298894527** [comment]
I don't know why you have this problem. The reason for this problem is that the user name of Microsoft login is Chinese, and the automatically generated file contains Chinese, so an error is reported. If you also have this problem, you may need to consider changing the login user name to English.

**Comment by kktt520** [comment]
thanks!!! That really helps.
