### ISSUE TITLE
getGEO: Error in downloadFile(myurl, destfile, mode) :

### ISSUE THREAD

**Issue by BolinZheng80** [seandavi/GEOquery#125]
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

gset<-getGEO("GSE144702",GSEMatrix=F,AnnotGPL=FALSE)
Timeout was reached: [] Operation timed out after 10005 milliseconds with 0 out of 0 bytes receivedFile stored at:
/var/folders/49/hgfwhy897qvfzl644czmmsgm0000gn/T//RtmpAuxZu1/GSE144702.soft.gz
Error in downloadFile(myurl, destfile, mode) : 
  Failed to download /var/folders/49/hgfwhy897qvfzl644czmmsgm0000gn/T//RtmpAuxZu1/GSE144702.soft.gz!

the getGEO doesn't work when i update the R recently, while it worked previously(R version 4.0).

Please help me out!

**Comment by seandavi** [comment]
Hi, @BolinZheng80. I am not able to reproduce this locally. The error you are receiving is a network timeout error. You can double-check that you can access the internet from R or retry the download later. I'm going to close for now since I don't think this error is related to GEOquery directly.
