### ISSUE TITLE
Error while using getGEOSuppFiles on macbook Air

### ISSUE THREAD

**Issue by AzlanNI** [seandavi/GEOquery#137]
Hello, 

i am currently trying to access data from GEO with the GEOquery Package. I tried the getGEO Command with the GEO Accession Number : GSE186458 which worked without problems. The Output was : 
 Found 1 file(s)
GSE186458_series_matrix.txt.gz
$GSE186458_series_matrix.txt.gz
ExpressionSet (storageMode: lockedEnvironment)
assayData: 0 features, 207 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: GSM5652176 GSM5652177 ... GSM5652382 (207 total)
  varLabels: title geo_accession ... tissue:ch1 (55 total)
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation: GPL24676 

After that i tried to access the data for this Accession Number with getGEOSuppFiles("GSE186458"). So here the Problem starts at first it downloads data without problems but after a short while i get the Output 

try URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE186nnn/GSE186458/suppl//GSE186458_RAW.tar?tool=geoquery'
Content type 'application/x-tar' length 132476723200 bytes (126339.6 MB)

downloaded 174.9 MB

error in getGEOSuppFiles("GSE186458") : 
  error to download /Users/azlannisar/GSE186458/GSE186458_RAW.tar!

So now i tried to watch up this Problem but was not successful with finding a solution. It cant be a memory issue since my Macbook has enough free space for the 126339.6 MB. 

So i would be glad if someone could help me out. If i find any other solution i will write again. 

Thanks!

Azlan

**To Reproduce**
Steps to reproduce the behavior including code example:

```
Code example
```

**Output of Session Info:**

```
Cut-and-paste output of sessionInfo
```

**Comment by seandavi** [comment]
The file you are downloading is 123GB in size. You are probably going to want to download that with a tool that allows the continuation of incomplete downloads since it is quite likely that the transfer could get interrupted. You can use the link in your error message with any other tool for downloading. Unfortunately, GEOquery and the tool that it uses to do the download doesn't do a continuation of downloads.
