### ISSUE TITLE
issue in designing a dataset matrix

### ISSUE THREAD

**Issue by MohaRamadan** [seandavi/GEOquery#142]
I'm using chatGPT to have the script to analyze a dataset about miRNA differential expression because I'm not a data specialist but when I reach the step of designing the matrix I have an error that I tried all the solutions given by chatGPT but nothing works
I don't know how to move on to avoid this error 
if anyone could help me that's will be great 
I will give the full script until I reach the step of error 

> library(limma)
> library(ggplot2)
> data <- read.table("C:/Users/Sci zoologist/Desktop/mmmmmm/GSE93810_processed_data.txt", header = TRUE, row.names = 1, sep = "\t")
> dim(data)
[1] 2549   56
> design <- data.frame(Group = c("normal expression", "high expression"), row.names = colnames(data))

and this is the error that I get every time 
> design <- data.frame(Group = c("normal", "high"), row.names = colnames(data))
Error in data.frame(Group = c("normal", "high"), row.names = colnames(data)) : 
  row names supplied are of the wrong length

**Comment by seandavi** [comment]
Hi, @MohaRamadan. This repository is for the GEOquery package. You might try asking your question on https://support.bioconductor.org/. ChatGPT can be helpful for general problems, but with specific datasets, it won't be that useful.
