### ISSUE TITLE
Better error messages for network connection problems

### ISSUE THREAD

**Issue by seandavi** [seandavi/GEOquery#15]

**Comment by ian1roberts** [comment]
Not sure if this is a related issue or something that affects only me - but more often than not, when trying to download series records with e.g.
```R
getGEO('GSE15852')
```
... FTP request hangs ... and nothing happens.
However when changing URLs to use http:// requests ... all is fine.
changes that worked for me are here https://github.com/ian1roberts/GEOquery/tree/master/R

Hope this is useful

**Comment by seandavi** [comment]
This is an old issue that has likely been largely resolved with the transition to https at NCBI.
