### ISSUE TITLE
error in the ftp site url when downloading supplement files for a GPL with getGEOSuppFiles

### ISSUE THREAD

**Issue by fouslim** [seandavi/GEOquery#16]
Hi Sean,

I think there is a typo in the GEO ftp site url when you download supplement files for a GPL with the function getGEOSuppFiles, **platform** should be replace by **platforms** (line 37 of the file getGEOSuppFiles.R):

> url <- sprintf("ftp://ftp.ncbi.nlm.nih.gov/geo/platform/%s/%s/suppl/",stub,GEO)
> url <- sprintf("ftp://ftp.ncbi.nlm.nih.gov/geo/platforms/%s/%s/suppl/",stub,GEO)

thanks

Slim Fourati
Sr Reaseach Associate
Department of Pathology, CWRU

**Comment by seandavi** [comment]
Closing an old issue. https is now used....
