### ISSUE TITLE
parseGPL reparses GPL files in the same session

### ISSUE THREAD

**Issue by leogama** [seandavi/GEOquery#23]
Hi,
In the current implementation, GEOquery already looks for a local version of a GPL file to avoid downloading it again. But when reading multiple GEO files associated with a single GPL soft file, it parses and loads into memory this same file multiple times, resulting in many identical copies of an AnnotatedDataFrame that represents the Platform! Below is a reproducible example:

``` R
R > gse32982 <- getGEO('GSE32982')
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE32nnn/GSE32982/matrix/
Found 1 file(s)
GSE32982_series_matrix.txt.gz
trying URL 'ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE32nnn/GSE32982/matrix/GSE32982_series_matrix.txt.gz'
ftp data connection made, file length 959302 bytes
==================================================
downloaded 936 KB

File stored at:
/tmp/Rtmpce6W06/GPL570.soft

R > gse45016 <- getGEO('GSE45016')
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE45nnn/GSE45016/matrix/
Found 1 file(s)
GSE45016_series_matrix.txt.gz
trying URL 'ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE45nnn/GSE45016/matrix/GSE45016_series_matrix.txt.gz'
ftp data connection made, file length 1486395 bytes
==================================================
downloaded 1.4 MB

Using locally cached version of GPL570 found here:
/tmp/Rtmpce6W06/GPL570.soft

R > gpl570_1 <- featureData(gse32982[[1]])
R > gpl570_2 <- featureData(gse45016[[1]])
R > identical(gpl570_1, gpl570_2)
[1] TRUE
R > data.table::address(gpl570_1)
[1] "0x10d32c78"
R > data.table::address(gpl570_2)
[1] "0x78835a0"
```

It's a waste of time and resources, since that caching the object originated from a specific file through the duration of the session shouldn't be hard to do.

**Comment by leogama** [comment]
My suggestion to optimize this is to have an internal `environment` where the `parseGPL` (or maybe the `.parseGPLWithLimits`) function could check for a cached version of the GPL object read from the file path passed as argument.

Some possible details necessary for this feature to work are:
- distinguish between objects that were parsed with different number of rows limits
- give the user an option to not use the cached version
- even if not explicitly specified, ignore the cached version if the original file was modified

Do you think this is reliable? It's just an initial idea...

**Comment by seandavi** [comment]
There are really two issues you have touched on:

1. Avoiding parsing the same GPL multiple times
2. A caching mechanism that is smart enough to keep GPLs around throughout a session.

I like the idea of number 1, but I would be concerned that keeping GPLs around in memory (number 2) might end up biting some users who don't realize this in-memory caching is going on.  I think what might make sense is the ability to pass in a list of GPL objects to getGEO() and getGEO would then check if a required GPL is already in the list.  If so, getGEO would use it and not download and reparse.  If not, the GPL would be fetched.  In a sense, we would leave caching to the user, making it less magical and less likely to catch new and "casual" users off-guard.  

So, I would propose adding another argument to getGEO:

getGEO(..., GPLlist = list(GPL, GPL, GPL, ...))

What do you think, @leogama?

**Comment by leogama** [comment]
You are right, these are two distinct features. But I didn't really
understand what are you worried about. Are you afraid of a "memory leak",
with GPLs siting around even after the associated objects have been
removed? To prevent this, I think we could use weak references in the
caching mechanism.

Or are you concerned about more subtle misbehavior? For example, if an user
is trying to modify a custom platform annotation file and rereading it
repeatedly, somehow getGEO could miss the file modification and return the
cached version instead? I don't know much about file systems, but if we are
very stringent in the file modification criteria, perhaps we can prevent
this too.

There's also a practical problem I can see in using the mechanism you
suggested: if the user wants to fetch a (maybe long) list of GEO Series or
Datasets, it possibly won't know in advance which platforms are associated
with these. When calling getGEO through lapply, there's not it can do about
and the GPL list becomes useless in this case - when it could give its most
benefit.

What I think is that we'll need to mature these ideas a bit more before
spending time with implementation details... =/ Do you think that the
effort pay off?

**Comment by leogama** [comment]
Of course, I forgot to mention that messaging the user about the use of a
cached GPL is probably enough to avoid any surprises. Actually, being
transparent throughout the entire process is essential.

If you still not confident with the caching, it could be implemented but
inactive by default.

Regards!

**Comment by seandavi** [comment]
Sorry to take so long to get back to you. How would you want to do the caching? In memory? On disk? If on disk, in what format?

**Comment by leogama** [comment]
I think @seandavi and me forgot to close this issue after merging #24. Mr. @assaron even developed his own file cache solution.

At the time, I thought the message displayed at the package loading was enough to give users a clue about this functionality. Should it be explicitly documented somewhere? Or maybe just add the word _cache_ to the option's name...
