### ISSUE TITLE
Cannot open URL

### ISSUE THREAD

**Issue by fgoebels** [seandavi/GEOquery#33]
> getGEO("GPL13112")
Error in download.file(myurl, destfile, mode = mode, quiet = TRUE, method = getOption("download.file.method.GEOquery")) : 
  cannot open URL 'http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GPL13112&form=text&view=full'

**Comment by seandavi** [comment]
I guess you figured out that this is an issue with NCBI having switched over to using HTTPS only.  An upgrade to GEOquery hopefully fixed your problem.  Let me know if that isn't the case, @fgoebels.

**Comment by fgoebels** [comment]
I figured it out after some time. First I tried to change to https by myself, only to realize that I should just update. Thanks for the quick response.

Thanks,
Florian

**Comment by seandavi** [comment]
Where should I post this so that folks will find it?  Any suggestions?
