### ISSUE TITLE
getGEO("GSExxxx") error

### ISSUE THREAD

**Issue by YairGatt** [seandavi/GEOquery#34]
Hello,
Retrieving data from GEO in the form of getGEO("GSExxxx") seems to produce errors that didn't occur before. Perhaps this is due to NCBI's recent move from http to https?

    >GSE <- getGEO("GSE3105")
    ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE3nnn/GSE3105/matrix/

    Found 1 file(s)
    GSE3105_series_matrix.txt.gz

    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100  251k  100  251k    0     0  70762      0  0:00:03  0:00:03 --:--:-- 70753
    File stored at:
    /tmp/RtmpnbTgfV/GPL199.soft
    Error in read.table(con, sep = "\t", header = FALSE, nrows = nseries) :
      invalid 'nlines' argument

Is this a known issue?
Yair

**Comment by seandavi** [comment]
Hi, @YairGatt.  Please make sure you are using the latest GEOquery.  If you have problems after upgrading, could you also send the output of `sessionInfo()`?  You are probably correct that this is related to the change to `https`, but that has been addressed in GEOquery's later versions.

**Comment by YairGatt** [comment]
Thank you for your swift reply.
After updating to the latest versions of R (3.3.1), Bioconductor (3.4) and GEOquery (2.40.0), everything is working fine!

**Comment by seandavi** [comment]
Great. Thanks for closing the loop.
