### ISSUE TITLE
Intermittent connection issues to GEO

### ISSUE THREAD

**Issue by seandavi** [seandavi/GEOquery#43]
> From: Hervé Pagès <hpages@fredhutch.org>
> Sent: Sep 27, 2017 7:27 PM
> To: "Davis, Sean (NIH/NCI) [E]" <sdavis2@mail.nih.gov>
> Cc: "Shepherd, Lori" <Lori.Shepherd@RoswellPark.org>
> Subject: intermittent GEO errors
> 
> Hi Sean,
> 
> We seem to get these intermittent GEO errors on our build reports
> pretty often these days, maybe more than usual. For example today
> we see them in release here:
> 
>  
> https://bioconductor.org/checkResults/3.5/bioc-LATEST/GEOquery/malbec2-checksrc.html
>  
> https://bioconductor.org/checkResults/3.5/bioc-LATEST/ChIPXpress/malbec2-checksrc.html
> 
> and in devel here:
> 
>  
> https://bioconductor.org/checkResults/3.6/bioc-LATEST/ChIPXpress/malbec1-checksrc.html
> 
> Do you have any idea why the GEO service is so flaky?
> 
> Are the sys admins in charge of ftp.ncbi.nlm.nih.gov aware of this?
> 
> Is there anything that could be done to improve this situation?
> 
> Was just wondering if you had any insight on this.
> 
> Thanks,
> H.

**Comment by seandavi** [comment]
@hpages and @lshep, wrote to NCBI GEO today to see what they think is going on. 

There are several other issues that are slightly related including #15, #31, and #33.

**Comment by hpages** [comment]
Thanks @seandavi !

**Comment by hpages** [comment]
FWIW GEOquery and ChIPXpress are not affected in today's build report but other packages are e.g. PGSEA on the Linux builder:

  https://bioconductor.org/checkResults/3.6/bioc-LATEST/PGSEA/malbec1-buildsrc.html

The set of affected packages changes everyday...

H.

**Comment by seandavi** [comment]
I pointed the NCBI GEO folks to this issue, so if any other details become available or relevant, we can drop them here for posterity sake. Thanks for the update, @hpages.

**Comment by kalugny** [comment]
@seandavi from looking at the logs, it's the same issue as #38 so it's not really a connection issue

**Comment by seandavi** [comment]
Fixed by 2955763. Thanks, everyone, for getting this sorted out.
