### ISSUE TITLE
getGEOSuppFiles function bug

### ISSUE THREAD

**Issue by ibilgen** [seandavi/GEOquery#63]
I am using getGEOSuppFiles function to download supplementary files for each of the series_id in the list. It usually returns an error after a progressing. The problem is that sometimes it gives error and stops but in some cases it works successfully. 

below the code, it shows the code I run and the error. The problem is seen in trying URL. After "..suppl//" part, a string starting with "mailto:" comes.

getGEOSuppFiles("GSE939", baseDir = "supp_files/", makeDirectory = T)
https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE939/suppl/
OK
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE939/suppl//mailto:%5bno%20address%20given%5d'
Error in download.file(file.path(url, i), destfile = file.path(storedir,  : 
  cannot open URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE939/suppl//mailto:%5bno%20address%20given%5d'
In addition: Warning message:
In download.file(file.path(url, i), destfile = file.path(storedir,  :
  cannot open URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE939/suppl//mailto:%5bno%20address%20given%5d': HTTP status was '404 Not Found'

**Comment by seandavi** [comment]
Thanks for the report, @ibilgen. I fixed this recently. The new behavior is to return `NULL` when no supplementary files are available. Could you update GEOquery the most recent version to check that is the behavior you now see?

**Comment by seandavi** [comment]
Closing for now. @ibilgen, feel free to update this issue if you are still noticing problems after upgrading. If you do, the output of `sessionInfo()` would be helpful.
