### ISSUE TITLE
getGEO() fails with some GSE records (looks like RNA-seq platforms) 

### ISSUE THREAD

**Issue by aeolianine** [seandavi/GEOquery#76]
Hi Sean,

Looks like parsing all RNA-seq GEO datasets (that I've tried) fails in the getGEO() function. Worked as of yesterday, no longer today (no upgrades/updates on my part). Code examples below:

library(GEOquery)

# here's an example that works, despite some parsing failures (all my microarray requests work)

> gse = getGEO('GSE39396')
Found 1 file(s)
GSE39396_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE39nnn/GSE39396/matrix/GSE39396_series_matrix.txt.gz'
Content type 'application/x-gzip' length 10637458 bytes (10.1 MB)
==================================================
downloaded 10.1 MB

Parsed with column specification:
cols(
  .default = col_double(),
  `1007_PM_s_at` = col_character()
)
See spec(...) for full column specifications.
File stored at: 
/var/folders/t0/gwjkb53d6nvcdvrrq8z911cj81zk69/T//Rtmp8xzKf6/GPL13158.soft
Warning: 102 parsing failures.
  row     col           expected    actual         file
54614 SPOT_ID 1/0/T/F/TRUE/FALSE --Control literal data
54615 SPOT_ID 1/0/T/F/TRUE/FALSE --Control literal data
54616 SPOT_ID 1/0/T/F/TRUE/FALSE --Control literal data
54617 SPOT_ID 1/0/T/F/TRUE/FALSE --Control literal data
54618 SPOT_ID 1/0/T/F/TRUE/FALSE --Control literal data
..... ....... .................. ......... ............
See problems(...) for more details.

# and here's an example that doesn't (all my Illumina HiSeq examples fail)

> gse = getGEO('GSE106288')
Found 1 file(s)
GSE106288_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE106nnn/GSE106288/matrix/GSE106288_series_matrix.txt.gz'
Content type 'application/x-gzip' length 2610 bytes
==================================================
downloaded 2610 bytes

Parsed with column specification:
cols()
Error in .subset2(x, i) : subscript out of bounds

Many thanks for your help,
Gergana

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2      GEOquery_2.50.0     Biobase_2.42.0      BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       tidyr_0.8.2      crayon_1.3.4     dplyr_0.7.8      assertthat_0.2.0
 [6] R6_2.3.0         magrittr_1.5     pillar_1.3.0     stringi_1.2.4    rlang_0.3.0.1   
[11] curl_3.2         rstudioapi_0.8   limma_3.38.3     xml2_1.2.0       tools_3.5.1     
[16] readr_1.2.1      glue_1.3.0       purrr_0.2.5      hms_0.4.2        yaml_2.2.0      
[21] compiler_3.5.1   pkgconfig_2.0.2  tidyselect_0.2.5 bindr_0.1.1      tibble_1.4.2

**Comment by aeolianine** [comment]
Thanks! Downgrading to readr 1.1.1 fixes this problem also.

**Comment by FerdinandoPucci** [comment]
No it does not

**Comment by seandavi** [comment]
Hi, @FerdinandoPucci. I haven't seen the behavior described above for over a year. Here is what I see with the current release of GEOquery (below). If you are having problems, be sure to upgrade to R-4.0.0 and then re-install all packages including GEOquery.

```
> gse = getGEO('GSE106288')
Found 1 file(s)
GSE106288_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE106nnn/GSE106288/matrix/GSE106288_series_matrix.txt.gz'
Content type 'application/x-gzip' length 2607 bytes
==================================================
downloaded 2607 bytes

Parsed with column specification:
cols(
  ID_REF = col_character(),
  GSM2834956 = col_character(),
  GSM2834957 = col_character(),
  GSM2834958 = col_character(),
  GSM2834959 = col_character(),
  GSM2834960 = col_character(),
  GSM2834961 = col_character(),
  GSM2834962 = col_character(),
  GSM2834963 = col_character(),
  GSM2834964 = col_character(),
  GSM2834965 = col_character(),
  GSM2834966 = col_character(),
  GSM2834967 = col_character(),
  GSM2834968 = col_character(),
  GSM2834969 = col_character()
)
File stored at: 
/var/folders/21/b_rp6qyj1_b1j5cp8qby0tnr0000gn/T//RtmpO8kOfM/GPL16791.soft
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GEOquery_2.56.0     Biobase_2.48.0      BiocGenerics_0.34.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        tidyr_1.0.3         crayon_1.3.4        dplyr_0.8.5        
 [5] assertthat_0.2.1    R6_2.4.1            lifecycle_0.2.0     magrittr_1.5       
 [9] pillar_1.4.4        stringi_1.4.6       rlang_0.4.6         curl_4.3           
[13] limma_3.44.1        xml2_1.3.2          vctrs_0.3.0         ellipsis_0.3.1     
[17] tools_4.0.0         readr_1.3.1         glue_1.4.1          purrr_0.3.4        
[21] hms_0.5.3           compiler_4.0.0      pkgconfig_2.0.3     BiocManager_1.30.10
[25] tidyselect_1.1.0    tibble_3.0.1       
```
