### ISSUE TITLE
GEOQuery inside of docker

### ISSUE THREAD

**Issue by jlevy44** [seandavi/GEOquery#77]
Hey there, I'm running GEOquery (using rpy2) inside of docker, wrapped using CWL. I'm trying to create a workflow that will let me download GEO files then analyze them. However, when running this script, I keep getting the following error after running it a few times:

geo.getGEOSuppFiles(query)

/opt/conda/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: No supplemental files found.

  warnings.warn(x, RRuntimeWarning)
/opt/conda/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Check URL manually if in doubt

  warnings.warn(x, RRuntimeWarning)
/opt/conda/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE107nnn/GSE107038/suppl/

  warnings.warn(x, RRuntimeWarning)
/opt/conda/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Error in file(con, "rb") : cannot open the connection

If you check the url, you can clearly see that there are supplemental files. What are your thoughts? I'm not sure what to do?

**Comment by jlevy44** [comment]
Could it be possible that #38 is at play here?

**Comment by seandavi** [comment]
Interesting use case. A couple of questions to start:

- Can you use curl/wget from within the container to access that URL?
- Does GEOquery behave correctly outside the container (on the same system)?

**Comment by jlevy44** [comment]
Oh, thanks!

Just reinstalled curl with conda inside the docker container and now it seems to work. I'll let you know if something like this happens again. Much appreciated!

Just so everyone knows, GEOquery works outside of the container on an hpc and wget was already installed. Here was the error I was getting before reinstalling curl:
curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Closing this issue! Thanks for the help.

**Comment by seandavi** [comment]
Love it when problems correct themselves....
