### ISSUE TITLE
The nature of the downloaded data (normalized vs nonnormalized?)

### ISSUE THREAD

**Issue by atakanekiz** [seandavi/GEOquery#81]
Hello,

Thanks for this very helpful package. I have a question about the nature of the data being downloaded by the `getGEO` function. I've analyzed a few datasets and when I plot the expression values of all the genes per sample I usually see similar distributions suggesting the data were normalized as seen below (example from GSE65218 gene expression microarray):

![image](https://user-images.githubusercontent.com/38366155/50863968-c638ac80-135d-11e9-9eab-fc9177f018a3.png)

But this isn't always true as seen here (example from protein mircoarray GSE25755):
![image](https://user-images.githubusercontent.com/38366155/50863929-a43f2a00-135d-11e9-987c-91befe91d1ba.png)

Median expression values are still not far away from each other which might indicate that some sort of normalization is applied. in the latter case as well. I just want to make sure that the data I download by using the `getGEO` function is always the normalized ready-to-analyze data. I'm using the default arguments to prepare the `ExpressionSet` object:

```
suppressPackageStartupMessages(library(GEOquery))

gse <- getGEO("GSE25755", destdir = getwd())

gse1 <- gse[[1]]
```

Thanks so much for the help.

Best,
Atakan

**Comment by seandavi** [comment]
Hi, @atakanekiz. The data downloaded by GEOquery are taken directly from the GEO repository without manipulation. In general, the data at GEO are taken directly from the submitters and are often normalized, but there is no guarantee that is the case. Also, the normalization methods (if at all) will vary from study to study. Often, the data processing approaches are detailed at GEO and that is the easiest way to determine what has been done. In some cases, you may have to go back to the publication or even to email the authors. 

Where raw data are available at GEO, you can also access those and process yourself if you want to thoroughly control the preprocessing. 

Hope that helps.

**Comment by atakanekiz** [comment]
That's very helpful, thank you very much.

Best,
Atakan
