### ISSUE TITLE
annotating `!Sample` in function 'parseGSEMatrix' 

### ISSUE THREAD

**Issue by wloof** [seandavi/GEOquery#82]
> Path: GEOquery/R/parseGEO.R
> Function: **parseGSEMatrix**
> GEO: 'GSE113249' or 'GSE113250'

#### Error:
```R
tmpdat <- read.table( fname, sep="\t", header=FALSE, nrows=samples_header_row_count,
                                   skip=sample_header_start-1)
```

#### Solution:
```R
tmpdat <- read.table( fname, sep="\t", header=FALSE, nrows=samples_header_row_count,
                                   skip=sample_header_start-1, fill = T )
```

**Comment by seandavi** [comment]
Thanks, @wloof, for the report. I am not seeing any errors with a current version of GEOquery. Could you clarify what error you are getting and what `sessionInfo()` looks like?

**Comment by wloof** [comment]
> 
> 
> Thanks, @wloof, for the report. I am not seeing any errors with a current version of GEOquery. Could you clarify what error you are getting and what `sessionInfo()` looks like?

Hi, @seandavi .
The real cause is the problem of coding.
In my windows, R local setting is 'Chinese'.
So I set
```R
Sys.setlocale("LC_ALL","English")
```
The problem is soveled.
The solution I mentioned before is wrong.
Thanks for your time.

**Comment by seandavi** [comment]
Ah, good to know! I'll see if there is a place to get that detail into the documentation.
