### ISSUE TITLE
Error in open.connection(x, "rb") : HTTP error 403.

### ISSUE THREAD

**Issue by dfantini82** [seandavi/GEOquery#86]
I think that the HTTPS protocol used to fetch data from the GEO server (for example, see "https://ftp.ncbi.nlm.nih.gov/geo/series/%s/%s/matrix/%s" in the getAndParseGSEMatrices() function) is deprecated. According to ftp://ftp.ncbi.nlm.nih.gov/geo/README.txt, the `https://` should be probably replaced with an `ftp://`.

Examples:

```
GSE88885 <- getGEO(GEO = "GSE88885")
# Error in open.connection(x, "rb") : HTTP error 403.

download.file("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE88nnn/GSE88885/matrix/", destfile = "TMP1")
# Error

download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE88nnn/GSE88885/matrix/", destfile = "TMP1")
# Works
```

**Comment by dfantini82** [comment]
Please, find below a very *quick and dirty* fix to the problem I ran into. This workaround was only tested on 1 single dataset and may not work for other datasets. I hope this could facilitate the work of the maintainer in addressing the issue. 

`
getGEO1 <- function (GEO = NULL, filename = NULL, destdir = tempdir(), GSElimits = NULL, 
                     GSEMatrix = TRUE, AnnotGPL = FALSE, getGPL = TRUE, parseCharacteristics = TRUE) 
{
  con <- NULL
  if (!is.null(GSElimits)) {
    if (length(GSElimits) != 2) {
      stop("GSElimits should be an integer vector of length 2, like (1,10) to include GSMs 1 through 10")
    }
  }
  if (is.null(GEO) & is.null(filename)) {
    stop("You must supply either a filename of a GEO file or a GEO accession")
  }
  if (is.null(filename)) {
    GEO <- toupper(GEO)
    geotype <- toupper(substr(GEO, 1, 3))
    if (GSEMatrix & geotype == "GSE") {
      return(getAndParseGSEMatrices1(GEO, destdir, AnnotGPL = AnnotGPL, 
                                     getGPL = getGPL, parseCharacteristics = parseCharacteristics))
    }
    filename <- getGEOfile(GEO, destdir = destdir, AnnotGPL = AnnotGPL)
  }
  ret <- parseGEO(filename, GSElimits, destdir, AnnotGPL = AnnotGPL, 
                  getGPL = getGPL)
  return(ret)
}




getDirListing1 <- function (url) 
{
  a <- xml2::read_html(url)
  fnames = gsub(".*(G[^[:space:]]+)[[:space:]].+", "\\1", a)
  return(fnames)
}


getAndParseGSEMatrices1 <- function (GEO, destdir, AnnotGPL, getGPL = TRUE, parseCharacteristics = TRUE) 
{
  GEO <- toupper(GEO)
  stub = gsub("\\d{1,3}$", "nnn", GEO, perl = TRUE)
  gdsurl <- "ftp://ftp.ncbi.nlm.nih.gov/geo/series/%s/%s/matrix/"
  
  b = getDirListing1(sprintf(gdsurl, stub, GEO))
  message(sprintf("Found %d file(s)", length(b)))
  ret <- list()
  for (i in 1:length(b)) {
    message(b[i])
    destfile = file.path(destdir, b[i])
    if (file.exists(destfile)) {
      message(sprintf("Using locally cached version: %s", 
                      destfile))
    } else {
      download.file(sprintf("ftp://ftp.ncbi.nlm.nih.gov/geo/series/%s/%s/matrix/%s", 
                            stub, GEO, b[i]), destfile = destfile, mode = "wb", 
                    method = getOption("download.file.method.GEOquery"))
    }
    ret[[b[i]]] <- GEOquery:::parseGSEMatrix(destfile, destdir = destdir, 
                                  AnnotGPL = AnnotGPL, getGPL = getGPL)$eset
  }
  return(ret)
}

# Now try, 
GSE88885 <- getGEO1(GEO = "GSE88885")
`

**Comment by seandavi** [comment]
I'll monitor, but this is a problem at NCBI, at least right now. If the problem persists after NCBI fixes its issue, we can reopen. In any case, thanks for the report of the problem.
