### ISSUE TITLE
Path to urls doesn't work

### ISSUE THREAD

**Issue by blancahimes** [seandavi/GEOquery#95]
Several of us tried using GEOquery today, as we have successfully in the past, but it seems like the links to GEO changed so now the queries do not find the proper files. For example,
> getGEOSuppFiles("GSE8823")
No supplemental files found.
Check URL manually if in doubt
https://ftp.ncbi.nlm.nih.gov/geo/series/GSE8nnn/GSE8823/suppl/
NULL
----
I checked the link, and indeed, it is missing. The raw files can still be found at https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE27973&format=file

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GEOquery_2.50.5     Biobase_2.42.0      BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       tidyr_1.0.0      zeallot_0.1.0    crayon_1.3.4     dplyr_0.8.3      assertthat_0.2.1
 [7] R6_2.4.0         lifecycle_0.1.0  backports_1.1.5  magrittr_1.5     pillar_1.4.2     rlang_0.4.1     
[13] curl_4.2         rstudioapi_0.10  limma_3.38.3     xml2_1.2.2       vctrs_0.2.0      tools_3.5.2     
[19] readr_1.3.1      glue_1.3.1       purrr_0.3.3      hms_0.5.2        compiler_3.5.2   pkgconfig_2.0.3 
[25] tidyselect_0.2.5 tibble_2.1.3

**Comment by seandavi** [comment]
NCBI has a habit of updating their ftp site "in place," leading to intermittent failures with finding files. It looks like the situation has resolved, at least for me. 

```
getGEOSuppFiles("GSE8823")
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE8nnn/GSE8823/suppl//GSE8823_RAW.tar?tool=geoquery'
Content type 'application/x-tar' length 542300160 bytes (517.2 MB)
```

Could you reopen this if things haven't resolved for you? 

Thanks for the report.

**Comment by blancahimes** [comment]
Thanks for the quick response! All is well now, and I will keep in mind for the future that NCBI links may be down for short periods of time. Funny that these things happen as several students try a command in real time that fails unexpectedly during a class.

**Comment by seandavi** [comment]
I've had that happen, also. The fallback is to use one of the GEO records packaged with GEOquery or to store the file of interest (often the series matrix file) in a separate location that students can download; GEOquery can parse the file directly.

**Comment by blancahimes** [comment]
Thanks again!
