### ISSUE TITLE
error in GEOquery

### ISSUE THREAD

**Issue by ezgicn** [seandavi/GEOquery#97]
if (!requireNamespace('BiocManager', quietly = TRUE))
  install.packages('BiocManager')
BiocManager::install('GEOquery')
library(GEOquery)

I wrote these codes above on the script but I had these answers below: (I use R3.6.2)

> library(GEOquery)
Error in library(GEOquery) : there is no package called ‘GEOquery’

**Comment by seandavi** [comment]
It looks like GEOquery did not install correctly. Are you working on Linux? Can you try re-installing and post the entire install output?

**Comment by ezgicn** [comment]
I use Windows10 :)

**Comment by ezgicn** [comment]
Now, I tried re-installing after cleaning global environment and console codes that I studied on and it was installed, thanks

**Comment by seandavi** [comment]
Fantastic. Let me know if you have more problems.
