### ISSUE TITLE
GSE134381 download error

### ISSUE THREAD

**Issue by davidechicco** [seandavi/GEOquery#99]
Hi
I am trying to download the GSE134381 dataset file through getGEO(), but apparently there are no data files at the indicated link.

I am using the following R commands:

```
setwd(".")
options(stringsAsFactors = FALSE)

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery)

GSE_code <- "GSE134381"
gset <- getGEO(GSE_code, GSEMatrix =TRUE, getGPL=FALSE)
```
and it generates the following error:

> Error in open.connection(x, "rb") : HTTP error 404.

Can you please make the data available again?

Thanks

-- Davide Chicco

**Comment by marickstarick** [comment]
Hi,

Did you solve the problem? I'm having the same error right now.

`gset <- getGEO(GSE_code, GSEMatrix =TRUE, getGPL=FALSE)`
`Error in open.connection(x, "rb") : HTTP error 404.`

**Comment by seandavi** [comment]
Hi, @davidechicco and @marickstarick. GEOquery has no relationship to the data provider, the NIH NCBI and the error you are seeing is stemming from a problem with NCBI. These kinds of problems happen intermittently, so if you wait a day, things might resolve. If not, do not hesitate to reach out to geo@ncbi.nlm.nih.gov about the data availability.

**Comment by marickstarick** [comment]
Thanks @seandavi,
The problem was temporarily solved by waiting some minutes and restarting R Studio.

**Comment by seandavi** [comment]
Just for reference, you don't need to restart Rstudio. The problem is entirely outside your system and resolves when NCBI GEO fixes things on their end. The magic is to wait a bit.
